name: ุญุฐู ุฎุฑูุทุฉ
description: ุงุณุชุฎุฏู ูุฐุง ุงููููุฐุฌ ูุญุฐู ุฎุฑูุทุฉ ููุฌูุฏุฉ ูู ุงููููุน.
title: "ุญุฐู ุฎุฑูุทุฉ"
labels: ["content-update", "delete-map"]
body:
  - type: input
    id: map-name
    attributes:
      label: ุงุณู ุงูุฎุฑูุทุฉ
      description: "ูุฌุจ ุฃู ูููู ุงูุงุณู ูุทุงุจูุงู ุชูุงูุงู ููุงุณู ุงูููุฌูุฏ ูู ุงููููุน."
    validations:
      required: true
  - type: dropdown
    id: channel
    attributes:
      label: ุงูููุงุฉ
      description: "ุงุฎุชุฑ ุงูููุงุฉ ุงูุชู ููุฌุฏ ูููุง ุงูููุฏูู."
      options:
        - "ููุงุชู ุงูุฃููู"
        - "ููุงุชู ุงูุซุงููุฉ"
    validations:
      required: true
  - type: input
    id: secret-token
    attributes:
      label: ๐ ุฑูุฒ ุงููุตุงุฏูุฉ
      description: "ุงูุฑุฌุงุก ุฅุฏุฎุงู ูููุฉ ุงูุณุฑ ุงูุฎุงุตุฉ ุจู ูุชุฃููุฏ ูุฐุง ุงูุชุบููุฑ."
    validations:
      required: true
